version: "3.0"

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - "env.influxdb"
    volumes:
      - influxdb-data:/var/lib/influxdb
      - $PWD/influxdb.conf:/etc/influxdb/influxdb.conf
    networks:
      covid19:
        aliases:
          - influxdb
    restart: always

  chronograf:
    image: chronograf:1.5
    container_name: cronograf
    ports:
        - 127.0.0.1:8087:8888
    volumes:
        - chronograf-data:/var/lib/chronograf
    networks:
      covid19:
        aliases:
          - cronograf
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - "env.grafana"
    volumes:
      - grafana-data:/var/lib/grafana
      - $PWD/grafana.ini:/etc/grafana/grafana.ini
    networks:
      covid19:
        aliases:
          - grafana
    restart: always

volumes:
  influxdb-data:
  grafana-data:
  chronograf-data:

networks:
  covid19:
