version: "3.0"

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - "env.influxdb"
    volumes:
      - influxdb-data:/var/lib/influxdb
      - $PWD/influxdb.conf:/etc/influxdb/influxdb.conf
    networks:
      influx:
        aliases:
          - influxdb
    restart: always

  chronograf:
    image: chronograf:1.5
    container_name: chronograf
    ports:
        - 127.0.0.1:8087:8888
    volumes:
        - chronograf-data:/var/lib/chronograf
    networks:
      influx:
        aliases:
          - chronograf
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - "env.grafana"
    volumes:
      - grafana-data:/var/lib/grafana
      - $PWD/grafana.ini:/etc/grafana/grafana.ini
    networks:
      influx:
        aliases:
          - grafana
    restart: always

  kapacitor:
    image: kapacitor
    container_name: kapacitor
    ports:
      - "9092:9092"
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    volumes:
      - kapacitor-data:/var/lib/kapacitor
      - $PWD/kapacitor.conf:/etc/kapacitor/kapacitor.conf
    networks:
      influx:
        aliases:
          - kapacitor
    restart: always

  telegraf:
    image: telegraf
    container_name: telegraf
    environment:
      HOSTNAME: telegraf
    volumes:
      - telegraf-data:/etc/telegraf/
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/telegraf.conf:/etc/telegraf/telegraf.conf
    networks:
      influx:
        aliases:
          - telegraf
    restart: always

volumes:
  influxdb-data:
  grafana-data:
  chronograf-data:
  kapacitor-data:
  telegraf-data:

networks:
  influx:
